# Generated by Django 5.2 on 2025-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
